apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: piikki-postgres
  namespace: piikki
spec:
  teamId: "piikki"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    majori:
      - superuser
  databases:
    piikki: majori
    piikki_client_tg: majori
  postgresql:
    version: "12"
