apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: helm-release-client-tg-secret-values
  namespace: piikki
spec:
  encryptedData:
    values.yaml: AgBD7MwdhBu9XvQfcM1pEKu3aOCQnumQOKrlhdHQ4GvLs3NB7SlgdVZ0BL028kWCW0GVDn9AuLz8kOMxUS1CNs+mQS7HspYzlEt/zdyDFUzVL58fmAkxpvqjBA1cj6AmLrfxFIrDhQXehynqvLQi6gtYhMiyj+A+Cdeg1RJK7zU5tn+45BKgSGaLXJSinu1P8r+bvLHKugWuoz6CJmOkJ/m5o/GGqBu735svEjsZdi5UEIQSykuKIsp0iAO234hlUPd/ewwRhaLG7wBpemDmeQI4pIFHUcH64CDhaR92wPy1RTZYu63xiBsbvYPsU4G5+6s772GzZMgC8IR5ahO3WHwmEVtyQ2dBJOyLzRToZgY62g62z+bSMe652gm7bnilaRimDc1tNIpwGgViujSwgs1QhD0Wct6mbwAyLNdQ1cbNG7+8NEPclcMW5Rwh//SthKUIfxVd+5bvJwnXUX4W6Tkh5z5ccX7CWX9a/eX+RoEqj9Nzid0rj9KsHItYOiW0K9JTKXMAMXdhsADWpP2cw9oBcrCzZGToj4QuBtL6eoYAoaNN98hSUV6lX9BfVgJteDDMlJPLdexoqy7Z+gQjq2Z0vEYL4QD8aLnK8+iOIWtDBZsmDZGn+VVeOWu37AT7+QL311laD9fQ6edwFxUKRhxbqC/74iPqjVsraPLPulNEJNY81ViftF1Z8VCgw2g/B5YPVJu7Zc4xbxd75X9HZjxUmOoAhm23FtLRFQ==
  template:
    metadata:
      creationTimestamp: null
      name: helm-release-client-tg-secret-values
      namespace: piikki

