---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: boris
  namespace: expl-bot
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: "semver:~0"
spec:
  chart:
    git: https://github.com/majori/expl-bot.git
    ref: master
    path: charts/expl-bot
  values:
    image:
      registry: ghcr.io
      repository: majori/expl-bot
      tag: 0.1.5
    postgres:
      host: expl-bot-postgres.expl-bot.svc.cluster.local
      database: boris_bot
      userSecret:
        name: majori.expl-bot-postgres.credentials.postgresql.acid.zalan.do
        key: username
      passwordSecret:
        name: majori.expl-bot-postgres.credentials.postgresql.acid.zalan.do
        key: password
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        cert-manager.io/acme-challenge-type: http01
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
          grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      host: boris-bot.majori.dev
      tls:
        secretName: expl-bot-boris-tls
  valuesFrom:
  - secretKeyRef:
      name: helm-release-boris-secret-values
      optional: false
