apiVersion: v1
kind: Pod
metadata:
  name: backuper-expl-bot
  namespace: expl-bot
  annotations:
    linkerd.io/inject: disabled
spec:
  containers:
    - name: backuper
      image: majori/postgresql-dropbox-backuper
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 250m
          memory: 126Mi
      env:
        - name: PG_HOSTNAME
          value: expl-bot-postgres.expl-bot.svc.cluster.local
        - name: PG_DATABASE
          value: expl_bot
        - name: PG_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres.expl-bot-postgres.credentials.postgresql.acid.zalan.do
              key: username
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres.expl-bot-postgres.credentials.postgresql.acid.zalan.do
              key: password
        - name: DROPBOX_TOKEN
          valueFrom:
            secretKeyRef:
              name: dropbox-token
              key: token
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: backup-encryption-password
              key: password
