apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: expl-bot-postgres
  namespace: expl-bot
spec:
  teamId: "expl-bot"
  volume:
    size: 1Gi
  numberOfInstances: 1
  enableLogicalBackup: true
  users:
    majori:
      - superuser
  databases:
    expl_bot: majori
    boris_bot: majori
  postgresql:
    version: "12"
