apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dropbox-token
spec:
  encryptedData:
    token: AgCFQau2vyOVBJbDOSefLsFUyGRjruIFvgps5xEw+h2VsSlyZHFAJAL9HYS3HZBYvhmZAblzS+uitrWESKmxie++eglynu1aIjMbHnuQlH/BMVOK7OR89x2Z4vzWKYUacwudrh3uKsi35lLkgspPZfLOjTB87fXIH120vMYKhT9ZFWtU4iC8i2vjzKCfzbqE6cnzCkEE1PPGBsE4zrwGDJd5UoGUD6tTUcEg8iWQhE3FY2qVmlO4fAcDxjfSmIVKGD8Fy9kmo6+/yzjkPzCY1U55ejUaq0g820qpdOw9QbSZarLwD5sbYYpkY4lCnrs1J5UHDQGL2IfPNSSiwPy94jbkw1tQHCaQ7U+4uhELEsaCC9EUbWgRMEvehfU5XGrTFfbPxHWV01FGI8T6Ufe/ZKQhALyubxVwwauo2VRTNE+3j9tx8KpxXQ9MONjsyPyHTFQGXPJ9V+iMFRFMyf1C3eHoAt10F4YtByEwS17WURRWb8o2/dxtK5jWQ8c5P5FJO9h5du7NILcLkv63Dji0cH1fUGQXE06tBhXHsROYapoMvirsCovI4cpFPYaoQPBNHuo2zmaqvFTRWK6Bnf9+Z4zfpJoVPkNluUe8Jrrp/v9CgS1LBuMfMXpX4ArOWKXXxl5+5ZHqjyudaQ5FRyxD2MKtBl0xiPuayHl4/evzzJulgzxlafVqfKvn5QjrvhFeRPX+aDhxdd0kTZ5lrEPbRDwqeInPXYIks18+eVpWvV0p7tZ94rRHsikR7xpfRxYNMEeXtZ5WcwmITkG6Wa47bEqS
  template:
    metadata:
      creationTimestamp: null
      name: dropbox-token
    type: Opaque

