apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: helm-release-main-secret-values
spec:
  encryptedData:
    values.yaml: AgAsw1QOgi+O9u6v3l3g4uGtVyG1mUUUwNuN9TQuUbF42yr/mdgr+OmVb/1drOWz0hkqwSOb1Qxj2FKjfGGOIrWzr1TkybgoZIHBzeYaVvHRjPMfD7JJr10qWaCD6UKdlhOwxhsQA0t08H/08OpGLjH9JpQN1ZeynLRnuCANnGC97Izaj23psJ/Y352ooEGE0NhTWhrt73z29QUfdnoQkOWtT1XCjIny97HRYI/129ftqGiU+q12v54wMPMYKh2miXzh1Jw2qUqZzysRP28L6h7YDjiGVJnnCYV3iCRdqoGgqxEkoyJVIiF292szMYqJ60AYOIk72Ivsk12isVlfDFtvgQUL8EIOH5CZh7GAk6cXsnZZvwJlLnbuCk6QgfonOnYBpOzCw8EgernuN+2kqT9dov8PqDjrmYhfo50U4SghMyDaTh4do1kngCBJyXPglgnlOWcJkGUvWVLc289HZXw+wykYOLh/T7egH/B+2hQQbsp85gaH9cYplnjndbRzvtpzPFm+tJDvwXXvWimBwSgBfcWcoI9g5LjB4wybs5wS3T6/F5tfaBz+rXogcHPm1UkB3VXkuPAh1fgEZLIBzT6iKTa3bMWrLzKmAbglg7sjGfSeEWOw+zwL23b8GEQVEei2jys7rRUF/dh+yE3oo1utRtujfRhz1z1Tn738e/fYOnHzfQSGx9m5rnsUmBFiTZ1SXLAaRf09NRzFd+yeBK0IQhP11RtL18EmnHZrR0wRIwVkZW+hVbZ9Jv3Xg7en1iUxkIwoiCB4P2s/Y2Rvf/LTKQ==
  template:
    metadata:
      creationTimestamp: null
      name: helm-release-main-secret-values
    type: Opaque

